version: '3'

services:
  proxy:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 8088 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/var/lib/docker/volumes/
  web:
    image: httpd  # this will use httpd:latest